version: '3.8'

services:
  # Frontend - Development Mode
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: agent-ai-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_OLLAMA_URL=http://imeso-ki-02:11434
      - VITE_COGNEE_URL=http://imeso-ki-02:8080
      # Cognee Environment Variables for Frontend
      - LLM_API_KEY=${LLM_API_KEY}
      - DATABASE_URL=sqlite:///app/data/cognee.db
      - COGNEE_DATA_DIR=/app/data
      # Additional development config
      - OLLAMA_URL=http://imeso-ki-02:11434
      - COGNEE_URL=http://imeso-ki-02:8080
    depends_on:
      - cognee
    networks:
      - agent-ai-network
    restart: unless-stopped
    extra_hosts:
      - "imeso-ki-02:host-gateway"

  # Cognee - AI Memory System
  cognee:
    image: cognee/cognee:main
    container_name: cognee-container
    ports:
      - "8080:8000"
    environment:
      # LLM Configuration
      - LLM_PROVIDER=${LLM_PROVIDER}
      - LLM_MODEL=${LLM_MODEL}
      - LLM_ENDPOINT=${LLM_ENDPOINT}
      - LLM_API_KEY=${LLM_API_KEY}
      # Embedding Configuration
      - EMBEDDING_PROVIDER=${EMBEDDING_PROVIDER}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - EMBEDDING_DIMENSIONS=${EMBEDDING_DIMENSIONS}
      - EMBEDDING_ENDPOINT=${EMBEDDING_ENDPOINT}
      - EMBEDDING_API_KEY=${EMBEDDING_API_KEY}
      # Database Configuration
      - DATABASE_URL=${DATABASE_URL}
      - COGNEE_DATA_DIR=${COGNEE_DATA_DIR}
    volumes:
      - cognee_data:/app/data
    networks:
      - agent-ai-network
    restart: unless-stopped
    extra_hosts:
      - "imeso-ki-02:host-gateway"

volumes:
  cognee_data:

networks:
  agent-ai-network:
    driver: bridge
